language: python
sudo: required
dist: xenial
python: "3.7"

install:
    - pip install tox
    - pip install cookiecutter
    - pip install coveralls

script: cookiecutter --no-input .; cd package; tox

after_success:
  - coveralls
