language: python
sudo: required
dist: xenial
python: "3.7"

install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - pip install tox
    - pip install cookiecutter
    - pip install coveralls

script: cookiecutter --no-input .; cd package; tox

after_success:
  - coveralls
