#!/bin/bash -x
shopt -s lastpipe; set +m;

# Detect if a release is made with semver keywords.
# If so, automatically bump version with semver using poetry

git rev-parse --show-toplevel | read BASE
version=$1
[[ $1 =~ (patch|minor|major|prepatch|preminor|premajor|prerelease) ]] && {
    # Disable not-poetry-based projects
    [[ -e $BASE/pyproject.toml ]] && {
            poetry version $1 --no-ansi -n | read -a poetry_response
            version=${poetry_response[5]}
            {
                git commit -m "chore: Version bump $version" pyproject.toml
                git checkout master;
                git merge develop;
                git checkout develop;
                git tag $version
                poetry run auto-changelog
                git tag -d $version
                git commit -m "chore: Changelog $version" CHANGELOG.md
                rm .git/LAST_FEATURE
                echo "$version" > .git/LAST_VERSION
            } &> ~/gflow_log
    }
}

echo $version
exit 0
